const storeKey='zoology-final-review-v1';
let state=JSON.parse(localStorage.getItem(storeKey)||'{"answers":{},"graded":{},"wrong":[]}');
let mode='chapter', current=0, type='all', order=[], mockIds=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const labels={choice:'Multiple Choice / 选择题',fill:'Fill-in / 填空题',judge:'True or False / 判断题',short:'Short Answer / 简答题'};
const normalize=s=>(s||'').toLowerCase().replace(/[\s，。、“”‘’；;,.()（）-]/g,'');
function save(){localStorage.setItem(storeKey,JSON.stringify(state));updateProgress()}
function allQuestions(){return chapters.flatMap(c=>c.questions.map(q=>({...q,chapter:c.id})))}
function activeQuestions(){let qs;if(mode==='mock'){if(!mockIds.length)mockIds=allQuestions().sort(()=>Math.random()-.5).slice(0,30).map(q=>q.id);const all=allQuestions();qs=mockIds.map(id=>all.find(q=>q.id===id))}else if(mode==='wrong')qs=allQuestions().filter(q=>state.wrong.includes(q.id));else qs=chapters[current].questions;return type==='all'?qs:qs.filter(q=>q.type===type)}
function setHeading(){const c=mode==='chapter'?chapters[current]:{id:mode==='mock'?'MOCK':'RETRY',title:mode==='mock'?'随机模拟卷':'错题重练',subtitle:mode==='mock'?'从全课程随机抽取 30 题。再次点击“随机模拟”可重新组卷。':'只显示曾经答错的题目。答对后会自动移出错题集。',summary:mode==='mock'?['覆盖全部章节','四种题型混合','提交后即时统计']:['针对性复习','保留原题解析','答对自动移除'],source:'题目均来自本课程课件整理。'};$('#chapterNumber').textContent=`CHAPTER ${c.id}`;$('#chapterTitle').textContent=c.title;$('#chapterSubtitle').textContent=c.subtitle;$('#knowledgeList').innerHTML=c.summary.map(x=>`<li>${x}</li>`).join('');$('#sourceNote').textContent='资料依据：'+c.source}
function render(){setHeading();let qs=activeQuestions();order=order.filter(id=>qs.some(q=>q.id===id));if(order.length!==qs.length)order=qs.map(q=>q.id);qs=order.map(id=>qs.find(q=>q.id===id));$('#questionList').innerHTML=qs.length?qs.map((q,i)=>card(q,i)).join(''):'<div class="question">这里暂时没有题目。先去章节练习答几道题吧。</div>';bindInputs();score(qs);$$('#chapterNav button').forEach((b,i)=>b.classList.toggle('active',mode==='chapter'&&i===current))}
function card(q,i){const saved=state.answers[q.id]??'';let input='';if(q.type==='choice')input=`<div class="options">${q.options.map((o,n)=>`<label class="option"><input type="radio" name="${q.id}" value="${n}" ${String(saved)===String(n)?'checked':''}> <span>${String.fromCharCode(65+n)}. ${o}</span></label>`).join('')}</div>`;if(q.type==='judge')input=`<div class="judge-options options"><label class="option"><input type="radio" name="${q.id}" value="true" ${String(saved)==='true'?'checked':''}>True</label><label class="option"><input type="radio" name="${q.id}" value="false" ${String(saved)==='false'?'checked':''}>False</label></div>`;if(q.type==='fill')input=`<input type="text" data-id="${q.id}" value="${saved}" placeholder="Enter your answer; separate multiple blanks with commas">`;if(q.type==='short')input=`<textarea data-id="${q.id}" placeholder="Write the key points. The system will give a keyword-based reference score.">${saved}</textarea>`;const graded=state.graded[q.id];return `<article class="question ${graded===true?'correct':graded===false?'wrong':''}" data-qid="${q.id}"><div class="qhead"><span class="qnum">Q${String(i+1).padStart(2,'0')}</span><span class="tag">${labels[q.type]}</span><span class="status">${graded===true?'✓':graded===false?'✕':''}</span></div><div class="prompt">${q.prompt}</div>${input}<div class="explanation ${graded!==undefined?'show':''}"><strong>Reference Answer / 参考答案：</strong>${answerText(q)}${q.answerEn&&q.answerText?`<br><span class="zh-answer">中文参考：${q.answerText}</span>`:''}<div class="explain-en"><b>Explanation:</b> ${q.explanationEn}</div><div class="explain-zh"><b>中文解析：</b>${q.explanationZh}</div><div class="keyword-result">${q.type==='short'&&graded!==undefined?keywordText(q,saved):''}</div></div></article>`}
function answerText(q){if(q.type==='choice')return `${String.fromCharCode(65+q.answer)}. ${q.options[q.answer]}`;if(q.type==='judge')return q.answer?'True / 正确':'False / 错误';return q.answerEn||q.answerText||q.answers.join(' / ')}
function keywordText(q,v){const hit=q.keywords.filter(k=>normalize(v).includes(normalize(k)));return `关键词命中：${hit.length}/${q.keywords.length}${hit.length?'（'+hit.join('、')+'）':''}`}
function bindInputs(){$$('#questionList input,#questionList textarea').forEach(el=>el.addEventListener('input',()=>{const id=el.dataset.id||el.name;state.answers[id]=el.type==='radio'?el.value:el.value;delete state.graded[id];save()}))}
function grade(q){const raw=state.answers[q.id];if(raw===undefined||normalize(String(raw))==='')return undefined;if(q.type==='choice')return Number(raw)===q.answer;if(q.type==='judge')return String(raw)===String(q.answer);if(q.type==='fill')return q.answers.some(a=>normalize(raw).includes(normalize(a)));const hits=q.keywords.filter(k=>normalize(raw).includes(normalize(k))).length;return hits>=Math.max(1,Math.ceil(q.keywords.length*.5))}
function gradeAll(){const qs=activeQuestions();let done=0,correct=0;qs.forEach(q=>{const r=grade(q);if(r!==undefined){state.graded[q.id]=r;done++;if(r){correct++;state.wrong=state.wrong.filter(id=>id!==q.id)}else if(!state.wrong.includes(q.id))state.wrong.push(q.id)}});save();render();toast(done?`已批改 ${done} 题，答对 ${correct} 题`:'请先作答')}
function score(qs){const graded=qs.filter(q=>state.graded[q.id]!==undefined);const ok=graded.filter(q=>state.graded[q.id]).length;$('#scoreValue').textContent=graded.length?Math.round(ok/graded.length*100)+'%':'—'}
function updateProgress(){const all=allQuestions(),done=all.filter(q=>state.graded[q.id]!==undefined).length;$('#progressText').textContent=`已完成 ${done} / ${all.length}`;$('#progressBar').style.width=`${done/all.length*100}%`}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function init(){chapters.forEach((c,i)=>$('#chapterNav').insertAdjacentHTML('beforeend',`<button data-index="${i}">${c.id} · ${c.title}</button>`));$('#chapterNav').addEventListener('click',e=>{if(!e.target.matches('button'))return;current=+e.target.dataset.index;mode='chapter';$$('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode==='chapter'));type='all';order=[];render();$('#sidebar').classList.remove('open')});$$('.mode').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;if(mode==='mock')mockIds=[];$$('.mode').forEach(x=>x.classList.toggle('active',x===b));order=[];render()});$('#typeFilters').onclick=e=>{if(!e.target.dataset.type)return;type=e.target.dataset.type;$$('#typeFilters button').forEach(x=>x.classList.toggle('active',x===e.target));order=[];render()};$('#gradeAll').onclick=gradeAll;$('#showAnswers').onclick=()=>{$$('.explanation').forEach(x=>x.classList.add('show'))};$('#shuffleQuestions').onclick=()=>{order=activeQuestions().map(q=>q.id).sort(()=>Math.random()-.5);render()};$('#toggleKnowledge').onclick=()=>{const ul=$('#knowledgeList'),open=ul.hidden;ul.hidden=!open;$('#sourceNote').hidden=!open;$('#toggleKnowledge span').textContent=open?'收起':'展开'};$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');$('#resetProgress').onclick=()=>{if(confirm('确定清空所有答案、成绩和错题记录吗？')){state={answers:{},graded:{},wrong:[]};save();render()}};render();updateProgress()}
init();
