const XC=(id,p,o,a,en,zh)=>({id,type:'choice',prompt:p,options:o,answer:a,explanationEn:en,explanationZh:zh});
const XJ=(id,p,a,en,zh)=>({id,type:'judge',prompt:p,answer:a,explanationEn:en,explanationZh:zh});
const XF=(id,p,ans,shown,en,zh)=>({id,type:'fill',prompt:p,answers:ans,answerEn:shown,answerText:shown,explanationEn:en,explanationZh:zh});
const XS=(id,p,k,a,en,zh)=>({id,type:'short',prompt:p,keywords:k,answerEn:a,answerText:a,explanationEn:en,explanationZh:zh});
const extra={
'01':[
XC('01c2','Which field studies the form and structure of animals?',['Ecology','Morphology','Etiology','Zoogeography'],1,'Morphology studies form and structure.','形态学研究动物的外形与结构。'),
XJ('01j2','Natural selection acts on heritable variation within populations.',true,'Heritable variation allows differential reproduction to alter trait frequencies.','可遗传变异使差异繁殖成功改变性状频率。'),
XC('01c3','Which observation best illustrates regulation?',['A lizard selecting different microhabitats to control body temperature','A fossil in rock','A moth emerging from a pupa','DNA replication'],0,'Behavioral thermoregulation maintains suitable internal conditions.','选择微生境调节体温属于调节作用。'),
XF('01f2','The inheritance model supported by Mendel is called ____ inheritance.',['particulate'],'particulate inheritance','Hereditary factors retain their identity rather than blending permanently.','遗传因子保持独立，而非永久混合。'),
XJ('01j3','Evolution necessarily proceeds toward greater complexity.',false,'Evolution has no predetermined goal; selection favors locally successful variants.','进化没有预定目标，只保留在特定环境中更成功的变异。')],
'10':[
XC('10c2','A shared derived character is called a ____.',['symplesiomorphy','synapomorphy','analogy','grade'],1,'Synapomorphies diagnose clades.','共衍征用于识别演化支。'),
XJ('10j2','A taxon containing an ancestor but not all descendants is paraphyletic.',true,'Excluding some descendants makes the group paraphyletic.','包含祖先但遗漏部分后代的是并系群。'),
XF('10f2','The two-part scientific name of a species consists of genus and ____.',['specific epithet','species epithet'],'specific epithet','Binomial nomenclature combines a genus name and a specific epithet.','双名法由属名和种加词组成。'),
XC('10c3','Which molecular sequence was classically used to compare the three domains of life?',['rRNA genes','Collagen only','Hemoglobin only','ATP itself'],0,'Ribosomal RNA genes provide broadly comparable phylogenetic information.','核糖体RNA基因可用于跨广泛类群的系统比较。'),
XJ('10j3','Similar structures always prove close common ancestry.',false,'Convergence can produce similarity without close relationship.','趋同演化可在亲缘较远类群中产生相似结构。'),
XS('10s2','How should you identify the sister group of a taxon on a cladogram?',['node','common ancestor','branch'],'Find the other lineage descending from the same immediate node; the two share the most recent common ancestor.','Sister groups share an immediate branching node.','姐妹群共享同一个最近分支节点。')],
'11':[
XC('11c2','Which structure is characteristic of apicomplexan parasites?',['Apical complex','Radula','Nematocyst','Trochophore'],0,'The apical complex helps penetrate host cells.','顶复合器帮助寄生虫侵入宿主细胞。'),
XJ('11j2','Euglena may combine photosynthesis with heterotrophic nutrition.',true,'Many euglenids are mixotrophic.','许多眼虫可进行混合营养。'),
XC('11c3','Red tides are often associated with blooms of ____.',['dinoflagellates','sponges','annelids','choanoflagellates'],0,'Dense dinoflagellate blooms can discolor water and release toxins.','甲藻大量繁殖可形成赤潮并产生毒素。'),
XF('11f2','The reproductive division that produces two daughter cells is binary ____.',['fission'],'fission','Binary fission is a common asexual process in protists.','二分裂是原生生物常见的无性繁殖方式。'),
XJ('11j3','Ciliates have only one functional type of nucleus.',false,'They typically possess somatic macronuclei and germ-line micronuclei.','纤毛虫通常同时具有大核和小核。'),
XS('11s2','State one feeding method used by protozoan-grade organisms.',['phagocytosis','absorption','photosynthesis'],'Examples include phagocytosis, absorption of dissolved nutrients, or photosynthesis in mixotrophs.','Feeding is diverse even within a single cell.','单细胞生物也具有吞噬、吸收或光合等多种营养方式。')],
'12':[
XC('12c2','Water normally leaves a sponge through the ____.',['ostia','osculum','spongocoel wall','spicule'],1,'The osculum is the large excurrent opening.','出水孔是海绵的大型出水开口。'),
XF('12f2','Small incurrent pores of a sponge are called ____.',['ostia','ostium'],'ostia','Ostia admit water into the canal system.','入水孔让水进入水沟系统。'),
XJ('12j2','Sponge cells can often reorganize after experimental dissociation.',true,'Their loose cellular organization permits remarkable reaggregation.','海绵细胞组织松散，解离后仍可重新聚合。'),
XC('12c3','Which canal system has the greatest filtering surface?',['Asconoid','Syconoid','Leuconoid','All equal'],2,'Leuconoid organization contains many flagellated chambers.','复沟型具有大量鞭毛室，过滤面积最大。'),
XJ('12j3','Sponges possess neurons and muscle cells organized into true tissues.',false,'They lack true nervous and muscular tissues.','海绵没有真正的神经和肌肉组织。'),
XS('12s2','Trace the basic direction of water flow through a sponge.',['ostia','canal','osculum'],'Water enters ostia, passes through canals or choanocyte chambers, and exits through the osculum.','Water flow supports feeding, respiration, and waste removal.','水流依次经过入水孔、水沟或领细胞室，最后由出水孔排出。')],
'13':[
XC('13c2','Cnidarians are primarily ____.',['triploblastic','diploblastic','acoelomate protostomes','segmented'],1,'Their body wall develops mainly from ectoderm and endoderm.','刺胞动物主要为两胚层动物。'),
XJ('13j2','A nerve net lacks a single centralized brain.',true,'Signals spread through a diffuse network.','神经网是弥散型系统，没有集中脑。'),
XC('13c3','Reef-building stony corals belong mainly to ____.',['Hydrozoa','Scyphozoa','Anthozoa','Cubozoa'],2,'Anthozoans include sea anemones and stony corals.','珊瑚纲包括海葵和石珊瑚。'),
XF('13f2','The specialized cnidarian cell containing a nematocyst is a ____.',['cnidocyte'],'cnidocyte','Cnidocytes are unique to the phylum.','刺细胞是刺胞动物门的独有细胞。'),
XJ('13j3','Anthozoans have a medusa stage in the normal life cycle.',false,'Anthozoans occur only as polyps.','珊瑚纲正常生活史只有水螅型。'),
XS('13s2','How do cnidarians digest a captured prey item?',['extracellular','gastrovascular','intracellular'],'Digestion begins extracellularly in the gastrovascular cavity and is completed intracellularly in gastrodermal cells.','Cnidarians combine two modes of digestion.','先在消化循环腔内细胞外消化，再由胃层细胞完成细胞内消化。')],
'14':[
XC('14c2','Which flatworm group includes tapeworms?',['Turbellaria','Cestoda','Monogenea','Rotifera'],1,'Cestodes are highly specialized intestinal parasites.','绦虫纲是高度特化的肠道寄生类群。'),
XJ('14j2','Tapeworms possess a complete digestive tract.',false,'They absorb nutrients across the tegument and lack a gut.','绦虫没有消化道，经体表吸收营养。'),
XF('14f2','The attachment organ at the anterior end of a tapeworm is the ____.',['scolex'],'scolex','Hooks or suckers on the scolex anchor the parasite.','头节上的吸盘或钩用于附着。'),
XC('14c3','A digestive tract with one opening is described as ____.',['complete','incomplete','coelomic','segmented'],1,'Food enters and waste leaves through the same opening.','不完全消化道只有一个开口。'),
XJ('14j3','Planarians can show strong regenerative ability.',true,'Neoblast stem cells support regeneration.','涡虫的成体干细胞支持强再生能力。'),
XS('14s2','Name two adaptations of parasitic flatworms.',['tegument','sucker','hooks','reproduction'],'Examples include a protective tegument, suckers or hooks, reduced sensory/digestive structures, and high reproductive output.','Parasites emphasize attachment, protection, and transmission.','寄生种常强化附着、保护与繁殖传播能力。')],
'16':[
XC('16c2','Torsion is characteristic of which molluscan class?',['Bivalvia','Gastropoda','Cephalopoda','Scaphopoda'],1,'Gastropod torsion rotates the visceral mass and mantle cavity.','腹足类扭转使内脏团和外套腔发生旋转。'),
XJ('16j2','Bivalve gills commonly function in both respiration and filter feeding.',true,'Ciliary currents move water and suspended particles across the gills.','双壳类鳃兼具呼吸和滤食作用。'),
XC('16c3','Which class includes octopuses and squids?',['Gastropoda','Cephalopoda','Monoplacophora','Polyplacophora'],1,'Cephalopods are active predatory molluscs.','头足类包括章鱼和乌贼。'),
XF('16f2','The rasping feeding organ of most molluscs is the ____.',['radula'],'radula','Rows of teeth on the radula scrape or cut food.','齿舌上的齿列用于刮取或切割食物。'),
XJ('16j3','The molluscan coelom is large and forms the main body cavity.',false,'The coelom is reduced; the hemocoel is the main body space in most molluscs.','软体动物真体腔退化，血腔构成主要体腔。'),
XC('16c4','Which structure allows a squid to use jet propulsion?',['Siphon/funnel','Byssus','Operculum','Style'],0,'Forceful water expulsion through the funnel produces thrust.','乌贼通过漏斗喷射水流产生推力。'),
XJ('16j4','Pearls form when mantle tissue deposits nacre around an irritant.',true,'Nacre is secreted in layers around the foreign material.','外套膜围绕异物分泌珍珠质形成珍珠。'),
XF('16f3','The larva shared by many molluscs and annelids is the ____ larva.',['trochophore'],'trochophore','This larval similarity supports lophotrochozoan relationships.','担轮幼虫的相似性支持冠轮动物的亲缘关系。'),
XS('16s2','Compare circulation in a typical bivalve and a cephalopod.',['open','closed','pressure'],'Bivalves have low-pressure open circulation; cephalopods have a high-pressure closed system supporting active predation.','Activity level is linked to circulatory performance.','双壳类为低压开放循环；头足类为高压闭管循环，适应主动捕食。'),
XS('16s3','Explain how the molluscan foot is modified in two different classes.',['foot','burrowing','arms','locomotion'],'Examples: a bivalve foot burrows; a gastropod foot creeps; a cephalopod foot forms arms and a funnel.','The same ancestral region supports different functions.','同源的足在不同类群中可变为掘穴足、爬行足或腕与漏斗。')],
'17':[
XC('17c2','The excretory organs repeated in many annelid segments are ____.',['nephridia','green glands','Malpighian tubules','flame bulbs only'],0,'Metanephridia collect coelomic fluid and modify it.','后肾管收集并处理体腔液。'),
XJ('17j2','Most annelids have a closed circulatory system.',true,'Blood remains mainly within vessels.','多数环节动物具有闭管循环。'),
XC('17c3','Parapodia are especially characteristic of many ____.',['polychaetes','leeches','earthworms','nematodes'],0,'Parapodia bear chaetae and aid movement and gas exchange.','多毛类疣足参与运动和气体交换。'),
XF('17f2','The thick reproductive band of an earthworm is the ____.',['clitellum'],'clitellum','It secretes mucus and forms the egg cocoon.','环带分泌黏液并形成卵茧。'),
XJ('17j3','Leeches usually possess abundant long chaetae on every segment.',false,'Leeches lack the typical chaetae of most annelids.','蛭类缺少多数环节动物具有的刚毛。'),
XS('17s2','How does an earthworm use circular and longitudinal muscles to crawl?',['circular','longitudinal','chaetae'],'Circular contraction lengthens segments; longitudinal contraction shortens them; chaetae anchor parts of the body against the substrate.','Alternating waves produce peristaltic movement.','环肌使体节伸长，纵肌使其缩短，刚毛交替固定，形成蠕动。')],
'18':[
XC('18c2','Which sensory structures are important in nematode chemoreception?',['Amphids','Ommatidia','Statocysts','Lateral lines'],0,'Amphids are anterior sensory organs.','双器是线虫前端重要感觉器官。'),
XJ('18j2','Nematodes possess a complete digestive tract with mouth and anus.',true,'One-way flow permits regional specialization.','线虫具有口和肛门，形成完整消化道。'),
XF('18f2','The hormone associated with molting in ecdysozoans is ____.',['ecdysone'],'ecdysone','Ecdysone coordinates biochemical steps of ecdysis.','蜕皮激素调控蜕皮过程。'),
XC('18c3','Trichinella spiralis is commonly acquired from ____.',['undercooked infected meat','mosquito bites','freshwater snails only','airborne spores'],0,'Encysted larvae in meat initiate infection when consumed.','食用含包囊幼虫的未熟肉可感染旋毛虫。'),
XJ('18j3','All nematodes are parasites.',false,'Many are free-living in soil, freshwater, and marine habitats.','大量线虫在土壤、淡水和海洋中自由生活。'),
XS('18s2','Give two features explaining the ecological success of nematodes.',['cuticle','reproduction','small','habitat'],'Possible features include a protective cuticle, small size, resistant stages, high reproduction, and a simple hydrostatic body plan.','Their design works in many habitats and hosts.','角质层、小体型、抗逆阶段、高繁殖率及流体静力骨骼促进其成功。')],
'20':[
XC('20c2','The main body space of a crustacean is the ____.',['coelom','hemocoel','spongocoel','pseudocoel'],1,'The hemocoel is derived largely from the persistent blastocoel.','甲壳动物主要体腔为血腔。'),
XJ('20j2','Crustacean appendages can be serially homologous yet perform different functions.',true,'A common biramous plan is modified into mouthparts, legs, and swimmerets.','同源双肢型附肢可特化为口器、步足和游泳足。'),
XC('20c3','The decapod antennal gland is also called the ____.',['green gland','coxal gland','flame gland','ink gland'],0,'Green glands filter and modify hemocoelic fluid.','十足目触角腺又称绿腺。'),
XF('20f2','Each photoreceptor unit of a compound eye is an ____.',['ommatidium','ommatidia'],'ommatidium','Many ommatidia together form a compound eye.','复眼由许多小眼组成。'),
XJ('20j3','Crustacean hemolymph may contain copper-based hemocyanin.',true,'Hemocyanin can give hemolymph a bluish color.','含铜的血蓝蛋白可使血淋巴呈蓝色。'),
XC('20c4','A crustacean statocyst mainly detects ____.',['balance and orientation','light color','salinity only','sound frequency'],0,'Statolith movement bends sensory setae.','平衡石移动刺激感觉刚毛，感受方位和平衡。'),
XJ('20j4','Isopods are typically laterally compressed, whereas amphipods are dorsoventrally flattened.',false,'The pattern is reversed: isopods are dorsoventrally flattened; amphipods are laterally compressed.','等足类背腹扁平，端足类左右侧扁。'),
XF('20f3','The resistant resting eggs of many branchiopods are called ____.',['ephippia','ephippium'],'ephippia','They survive cold and desiccation.','枝角类抗性休眠卵可耐寒和干燥。'),
XS('20s2','Explain hormonal control of crustacean molting.',['X-organ','inhibiting','Y-organ','ecdysone'],'Reduced molt-inhibiting hormone from the X-organ permits Y-organs to release ecdysone, initiating ecdysis.','Eyestalk neurosecretion normally restrains molting.','X器官蜕皮抑制激素下降，使Y器官释放蜕皮激素并启动蜕皮。'),
XS('20s3','Contrast apposition and superposition vision in crustaceans.',['bright','dim','apposition','superposition'],'Apposition isolates ommatidia for a precise mosaic in bright light; superposition combines rays for a brighter but less precise image in dim light.','Pigment migration changes optical coupling.','明处并置眼图像清晰；暗处叠加眼提高感光但精度较低。')],
'21':[
XC('21c2','Which insect tagma bears wings when wings are present?',['Head','Thorax','Abdomen','Cerci'],1,'Wings arise from the mesothorax and metathorax.','昆虫翅着生于中胸和后胸。'),
XJ('21j2','The insect exoskeleton is composed mainly of chitin and protein.',true,'It protects the body and provides muscle attachment.','昆虫外骨骼主要由几丁质和蛋白质构成。'),
XF('21f2','The main insect excretory organs are ____ tubules.',['malpighian'],'Malpighian tubules','They remove wastes from hemolymph into the gut.','马氏管把血淋巴中的废物送入肠道。'),
XC('21c3','Which mouthpart type is characteristic of butterflies?',['Chewing','Siphoning','Sponging only','Piercing mandibles'],1,'The coiled proboscis siphons nectar.','蝶类卷曲口器用于虹吸花蜜。'),
XJ('21j3','A pupa is present in incomplete metamorphosis.',false,'Incomplete metamorphosis proceeds through nymphs without a pupa.','不完全变态只有若虫期，没有蛹期。'),
XC('21c4','Which feature helps terrestrial insects conserve water?',['Closable spiracles and waxy cuticle','External gills','Very permeable skin','Dilute urine'],0,'These reduce respiratory and surface water loss.','可关闭气门和蜡质表皮可减少失水。'),
XF('21f3','The juvenile stage resembling a small adult in incomplete metamorphosis is a ____.',['nymph'],'nymph','Nymphs grow through successive molts.','若虫经多次蜕皮逐渐长大。'),
XS('21s2','Why can insect flight promote evolutionary diversification?',['dispersal','escape','food','mate'],'Flight improves dispersal, access to food and mates, predator escape, and colonization of new habitats.','Mobility opens many ecological opportunities.','飞行增强扩散、觅食、求偶、逃避捕食及新生境定殖。')],
'23':[
XC('23c2','In tunicates, most hallmark chordate features are clearest in the ____.',['sessile adult','tadpole larva','egg only','colonial zooid only'],1,'The motile larva has a notochord, nerve cord, and postanal tail.','尾索动物蝌蚪幼体最清楚显示脊索特征。'),
XJ('23j2','Cephalochordates retain the notochord throughout life.',true,'The notochord extends into the anterior body and persists in adults.','头索动物终生保留脊索。'),
XF('23f2','The neural crest is a major evolutionary innovation of ____.',['vertebrates','vertebrata'],'vertebrates','Neural crest cells contribute to jaws, sensory structures, and more.','神经嵴参与形成颌、感觉结构等，是脊椎动物重要创新。'),
XC('23c3','The endostyle of amphioxus primarily aids ____.',['filter feeding','jet propulsion','venom injection','urine formation'],0,'It secretes mucus that traps food particles.','内柱分泌黏液捕获食物颗粒。'),
XJ('23j3','Amphioxus has a distinct vertebrate-like head with elaborate sense organs.',false,'It lacks a distinct head and specialized vertebrate sense organs.','文昌鱼缺少明显头部和复杂特化感觉器官。'),
XC('23c4','The notochord mainly provides ____.',['axial support','digestion','excretion','hormone secretion'],0,'It is a flexible longitudinal supporting rod.','脊索是柔性的纵向支持结构。'),
XF('23f3','Chordate pharyngeal openings are called pharyngeal pouches or ____.',['slits'],'slits','They function in feeding or respiration in different groups.','咽裂在不同类群中参与滤食或呼吸。'),
XS('23s2','Contrast adult tunicates with amphioxus in retention of chordate features.',['tunicate','metamorphosis','amphioxus','retain'],'Adult tunicates lose several larval chordate features during metamorphosis; amphioxus retains the basic chordate plan throughout life.','Their different adult lifestyles explain much of the contrast.','尾索动物变态后丢失多项特征；文昌鱼终生保留基本脊索体制。')],
'24':[
XC('24c2','Which living jawless fish lacks true vertebrae?',['Hagfish','Lamprey','Shark','Lungfish'],0,'Hagfishes retain a cranium but lack true vertebrae.','盲鳗有头骨但没有真正椎骨。'),
XJ('24j2','Lampreys possess a suctorial oral disc and many are parasitic.',true,'They attach to fishes and rasp tissues.','七鳃鳗以吸盘状口附着并刮食宿主组织。'),
XC('24c3','Shark scales are called ____.',['placoid scales','ctenoid scales','cycloid scales','ganoid scales'],0,'Placoid scales resemble small teeth.','盾鳞结构类似小型牙齿。'),
XF('24f2','The buoyancy organ of most ray-finned bony fishes is the ____ bladder.',['swim'],'swim bladder','Gas volume adjusts buoyancy.','鳔通过调节气体体积控制浮力。'),
XJ('24j3','Sharks usually rely on a swim bladder for static buoyancy.',false,'They lack a swim bladder and use lift, oily liver, and body composition.','鲨鱼没有鳔，依靠游动升力和富油肝脏等维持浮力。'),
XC('24c4','Countercurrent flow in fish gills improves ____.',['oxygen extraction','urine concentration only','vision','hearing'],0,'Opposite water and blood flow preserves a diffusion gradient.','水流与血流相反可维持氧扩散梯度。'),
XF('24f3','The cartilaginous fish intestine often contains a ____ valve.',['spiral'],'spiral valve','It increases absorptive area without a very long intestine.','螺旋瓣在较短肠道内增加吸收面积。'),
XJ('24j4','A four-chambered fish heart pumps oxygenated blood directly to the body.',false,'Typical fishes have a two-chambered pumping heart and single circulation.','典型鱼类为一心房一心室的单循环。'),
XC('24c5','Which fins chiefly provide paired control surfaces?',['Pectoral and pelvic','Dorsal and anal only','Caudal only','Adipose only'],0,'Paired fins aid steering, braking, and balance.','胸鳍和腹鳍参与转向、制动和平衡。'),
XJ('24j5','Lobe-finned fishes are especially important to tetrapod ancestry.',true,'Tetrapod limbs evolved within the sarcopterygian lineage.','四足动物肢体起源于肉鳍鱼支系。'),
XS('24s2','Describe the basic path of blood in fish single circulation.',['heart','gills','body'],'Heart → gills for oxygenation → body tissues → heart.','Blood passes through the heart once per circuit.','血液由心脏到鳃，再到全身，最后回心，每循环只过心一次。'),
XS('24s3','Give two adaptations that reduce drag during swimming.',['streamlined','mucus','scales','fins'],'A streamlined body, smooth scales and mucus, and controlled fin placement reduce turbulence and drag.','Shape and surface both matter.','流线体形、平滑鳞片与黏液以及鳍的控制都能减少阻力。')],
'25':[
XC('25c2','Which Devonian fish lineage gave rise to tetrapods?',['Lobe-finned fishes','Ray-finned fishes only','Sharks','Hagfishes'],0,'Tetrapods arose within sarcopterygians.','四足动物起源于肉鳍鱼类。'),
XJ('25j2','Air contains more oxygen than water but provides much less buoyancy.',true,'This makes respiration easier but support more difficult.','空气含氧多，但浮力远低于水。'),
XF('25f2','Salamanders belong to the order ____.',['urodela','caudata'],'Urodela (Caudata)','Adults generally retain a tail.','有尾目成体通常保留尾。'),
XC('25c3','Caecilians belong to ____.',['Gymnophiona','Anura','Urodela','Testudines'],0,'Caecilians are limbless burrowing amphibians.','蚓螈是无足、善掘穴的两栖类。'),
XJ('25j3','Amphibian skin is generally thick, dry, and impermeable.',false,'It is thin and moist and often participates in gas exchange.','两栖类皮肤薄而湿润，常参与气体交换。'),
XC('25c4','The transformation from tadpole to adult frog is strongly controlled by ____.',['thyroid hormones','insulin only','ecdysone','juvenile hormone'],0,'Thyroid hormones coordinate amphibian metamorphosis.','甲状腺激素调控两栖类变态。'),
XF('25f3','Gas exchange across the skin is called ____ respiration.',['cutaneous'],'cutaneous respiration','Moist vascular skin permits diffusion.','湿润且富血管的皮肤可进行皮肤呼吸。'),
XJ('25j4','Most amphibians are ectothermic.',true,'Body temperature depends substantially on environmental heat.','多数两栖类为外温动物。'),
XS('25s2','Summarize the major changes during frog metamorphosis.',['legs','tail','gills','lungs','gut'],'Limbs develop, the tail and gills regress, lungs and eyelids mature, and feeding and digestive structures reorganize.','Metamorphosis shifts an aquatic larva toward a terrestrial adult.','蛙变态包括生肢、尾和鳃退化、肺与眼睑发育及消化系统重组。'),
XS('25s3','Why must most amphibian eggs remain in water or moist sites?',['shell','desiccation','jelly'],'They lack a protective shell and have jelly coats permeable to water, so embryos are vulnerable to desiccation.','Reproduction remains tied to moisture.','两栖卵无保护性外壳，胶质卵膜易失水，因此繁殖依赖湿润环境。')],
'26':[
XC('26c2','A skull with two temporal openings on each side is ____.',['anapsid','synapsid','diapsid','apsid'],2,'Most reptiles, including birds, belong to the diapsid lineage.','多数爬行动物及鸟类属于双颞孔支系。'),
XJ('26j2','Internal fertilization is an important component of reproduction away from water.',true,'Gametes are protected from desiccation before the shelled egg is laid.','体内受精在产壳卵前保护配子免于干燥。'),
XF('26f2','The membrane surrounding allantois and amnion and aiding gas exchange is the ____.',['chorion'],'chorion','The chorion lies beneath the porous shell.','绒毛膜位于多孔卵壳之下并参与气体交换。'),
XC('26c3','The only living representatives of Sphenodonta are ____.',['tuataras','turtles','crocodiles','snakes'],0,'Tuatara are relicts of an ancient lineage.','楔齿蜥是古老喙头类的现生孑遗。'),
XJ('26j3','Snakes lack all traces of paired appendages in every species.',false,'Some snakes retain vestigial pelvic girdles and spurs.','部分蛇仍保留退化腰带和距。'),
XC('26c4','Crocodilians have a heart with ____.',['two chambers','three chambers','four chambers','no atria'],2,'Their complete ventricular separation supports efficient circulation.','鳄类具有四腔心脏。'),
XF('26f3','The keratinized epidermal scales of reptiles chiefly reduce ____ loss.',['water'],'water','A dry cornified skin supports terrestrial life.','角质化干燥皮肤可减少水分散失。'),
XJ('26j4','Temperature-dependent sex determination occurs in some reptiles.',true,'Incubation temperature can influence gonadal development.','部分爬行动物性别受孵化温度影响。'),
XS('26s2','Compare ectothermy with endothermy in energetic terms.',['external','metabolic','energy','food'],'Ectotherms rely largely on external heat and need less food; endotherms generate metabolic heat, allowing stable activity at greater energy cost.','The trade-off is low cost versus thermal independence.','外温动物依赖外界热源、耗能低；内温动物代谢产热、活动稳定但食物需求高。'),
XS('26s3','Name two adaptations that reduce water loss in reptiles.',['scales','uric acid','shell','behavior'],'Examples include keratinized scales, uric-acid excretion, shelled eggs, efficient kidneys, and water-conserving behavior.','Multiple systems support terrestrial water balance.','角质鳞、尿酸排泄、壳卵及节水行为等共同减少失水。')],
'27':[
XC('27c2','The principal protein of feathers is ____.',['keratin','collagen','chitin','cellulose'],0,'Feathers are keratinized epidermal structures.','羽毛是角蛋白化的表皮结构。'),
XJ('27j2','Penguins are birds even though their wings are modified for swimming.',true,'Flightlessness does not remove other avian synapomorphies.','企鹅虽不能飞，但仍具有鸟类共有特征。'),
XF('27f2','The large breastbone projection anchoring flight muscles is the ____.',['keel','carina'],'keel (carina)','A large keel supports powerful pectoral muscles.','龙骨突为强大的胸肌提供附着面。'),
XC('27c3','Bird bones connected to air sacs are described as ____.',['pneumatic','cartilaginous','solid marrow bones only','placoid'],0,'Pneumatic bones reduce mass while maintaining structural organization.','含气骨有助于减轻体重。'),
XJ('27j3','Bird lungs expand and contract like mammalian lungs.',false,'Rigid lungs receive airflow driven by expanding air sacs.','鸟肺较刚性，气囊的扩张收缩推动气流。'),
XC('27c4','Bird nitrogenous waste is excreted mainly as ____.',['ammonia','urea','uric acid','nitrate'],2,'Uric acid conserves water and can be stored safely in the egg.','尿酸节水，也适合在卵内积累。'),
XF('27f3','The muscular stomach chamber that grinds food is the ____.',['gizzard'],'gizzard','Ingested grit may assist mechanical breakdown.','肌胃可借助砂粒机械研磨食物。'),
XJ('27j4','Feathers provide insulation as well as aerodynamic surfaces.',true,'Contour and down feathers serve different mechanical and thermal roles.','羽毛兼具空气动力和保温作用。'),
XC('27c5','A single occipital condyle allows birds to ____.',['rotate the head extensively','chew with molars','breathe through skin','form a diaphragm'],0,'The skull-neck joint permits substantial head mobility.','单枕髁使鸟类头部转动灵活。'),
XJ('27j5','Seasonal migration can reduce exposure to climatic extremes.',true,'Migration helps maintain favorable feeding and breeding conditions.','迁徙可避开极端气候并获得适宜繁殖和食物条件。'),
XS('27s2','Explain the two-cycle movement of one parcel of air through a bird respiratory system.',['posterior','lung','anterior','exhalation'],'First inhalation sends air to posterior sacs; first exhalation moves it through lungs; second inhalation sends it to anterior sacs; second exhalation expels it.','Air sacs maintain near-continuous lung flow.','一次气团需两次吸呼：后气囊→肺→前气囊→体外。'),
XS('27s3','How do birds reduce body mass without sacrificing major functions?',['beak','air sacs','pneumatic','ovary'],'Examples include toothless beaks, pneumatic bones, air sacs, loss of some organs, and one functional ovary in most females.','Mass reduction is combined with structural reinforcement.','无齿喙、含气骨、气囊、部分器官退化及雌鸟单侧卵巢等减轻体重。')],
'28':[
XC('28c2','Which feature most directly separates mammalian teeth into incisors, canines, premolars, and molars?',['Heterodonty','Homodonty','Torsion','Tagmatization'],0,'Heterodont dentition supports specialized food processing.','异型齿使不同牙齿承担专门功能。'),
XJ('28j2','Most mammals replace their teeth only once.',true,'Diphyodont dentition includes deciduous and permanent sets.','多数哺乳动物为双套牙。'),
XF('28f2','The muscular sheet separating thoracic and abdominal cavities is the ____.',['diaphragm'],'diaphragm','Its contraction ventilates the lungs.','横膈膜收缩参与肺通气。'),
XC('28c3','Egg-laying mammals are ____.',['monotremes','marsupials','placentals','cetaceans'],0,'Monotremes include platypuses and echidnas.','单孔类包括鸭嘴兽和针鼹。'),
XJ('28j3','Marsupial young usually complete much development attached to a teat.',true,'Gestation is short and lactational development prolonged.','有袋类妊娠较短，幼体常附着乳头继续发育。'),
XC('28c4','The mammalian middle ear contains ____.',['one ossicle','two ossicles','three ossicles','no ossicles'],2,'Malleus, incus, and stapes transmit sound.','锤骨、砧骨和镫骨传导声音。'),
XF('28f3','Heat production that maintains a relatively stable body temperature is ____.',['endothermy'],'endothermy','Metabolic heat supports activity across diverse climates.','内温性依靠代谢产热维持较稳定体温。'),
XJ('28j4','All mammals give birth to live young.',false,'Monotremes lay eggs.','单孔类哺乳动物仍然产卵。'),
XC('28c5','Which brain region became especially enlarged in mammals?',['Cerebral cortex','Medulla only','Spinal cord only','Pineal eye'],0,'The enlarged cortex supports learning, integration, and flexible behavior.','发达的大脑皮层支持学习、信息整合和灵活行为。'),
XJ('28j5','Hair can function in insulation, sensation, signaling, and waterproofing.',true,'Mammalian hair has diversified beyond insulation.','毛发除保温外，还可承担感觉、信号和防水功能。'),
XS('28s2','Compare monotreme, marsupial, and placental reproduction.',['egg','pouch','placenta','gestation'],'Monotremes lay eggs; marsupials have short gestation and prolonged teat-associated development; placentals typically support longer uterine development through a complex placenta.','These are three living reproductive strategies.','单孔类产卵；有袋类短妊娠、乳头上继续发育；胎盘类通常借复杂胎盘长期宫内发育。'),
XS('28s3','Give three mammalian adaptations supporting sustained activity.',['endothermy','diaphragm','heart','teeth','brain'],'Examples include endothermy and hair, alveolar lungs with a diaphragm, four-chambered heart, heterodont teeth, and an enlarged brain.','Multiple systems jointly support high activity.','内温与毛发、肺泡肺和横膈膜、四腔心、异型齿及发达脑共同支持持续活动。')]
};
chapters.forEach(ch=>ch.questions.push(...(extra[ch.id]||[])));
